services:
  mydb:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - user_backend
    ports:
      - "5432:5432"
    volumes:
      - mydb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d mydb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - user_backend
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - user_backend
    ports:
      - "8081:8081"

  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: user-service
      ports:
        - "8080:8080"
      depends_on:
        mydb:
          condition: service_healthy
        redis:
          condition: service_started
      env_file:
        - .env
      networks:
        - shared_network
        - user_backend
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - SPRING_DATASOURCE_URL=jdbc:postgresql://mydb:5432/mydb
        - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
        - REDIS_HOST=redis
        - REDIS_PORT=${REDIS_PORT}
        - JWT_SECRET=${JWT_SECRET}

volumes:
  mydb_data:
  redis_data:
networks:
  user_backend:
    driver: bridge
  shared_network:
    external: true