spring.application.name=user-service
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.data.web.pageable.serialization-mode=via_dto

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}