spring.datasource.url=${DATABASE_LOCAL_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.data.redis.host=${REDIS_LOCAL_HOST}
spring.data.redis.port=${REDIS_PORT}