spring.datasource.url=jdbc:postgresql://mydb:5432/mydb
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}