spring.application.name=user-service
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.data.web.pageable.serialization-mode=via_dto
spring.cache.type=redis
spring.jpa.hibernate.ddl-auto=validate

spring.profiles.active=local