spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.data.redis.host=${REDIS_LOCAL_HOST}
spring.data.redis.port=${REDIS_PORT}
jwt.secret=${JWT_SECRET}