name: build-and-deploy

on:
  push:
    branches: [ "main" , "AuthService" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Coverage
        run:  mvn -B -DskipTests=false clean verify

      - name: Debug Jacoco XML
        run: ls -l target/site

      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Package JAR
        run: mvn package -Dmaven.test.skip=true -Djacoco.skip=true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/user-service" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}